# Generated by Django 2.2.1 on 2019-05-15 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190515_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
