# Generated by Django 2.2.1 on 2019-05-16 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190515_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
